# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsystem',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingsystem',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
